### ISSUE TITLE
Uplaoded video not playing

### ISSUE THREAD

**Issue by ToniNgethe** [Ronit94/resumable-video-upload#1]

**Comment by Ronit94** [comment]
the process is configured in such a way that  after the uploaded it considered as a binary file which certainly not playable. So give me some time to modify this process.

**Comment by ToniNgethe** [comment]
hi, were you able to modify?

**Comment by Ronit94** [comment]
Tus provides some of core events, one of them is EVENT_UPLOAD_COMPLETE, from the client end you are already sending file information (extension, name) extract that data on this event when the file is totally uploaded then using fs module copy or rename that binary file with the filename and extension , certainly it will play. Try that if still issue remaining then I will update the repo with this feature

**Comment by ToniNgethe** [comment]
kindly do.

**Comment by Ronit94** [comment]
@ToniNgethe please check my updated repo, I have implemented the logic and now you can use the file after completion.
